export const dataMock = [
  {
    "id": "HAPa1bD",
    "title": "Imagem 1",
    "description": null,
    "datetime": 1671564948,
    "cover": "W6BU06r",
    "cover_width": 670,
    "cover_height": 961,
    "account_url": "Sodaman18",
    "account_id": 167021773,
    "privacy": "hidden",
    "layout": "blog",
    "views": 44,
    "link": "https:\/\/imgur.com\/a\/HAPa1bD",
    "ups": 9,
    "downs": 2,
    "points": 7,
    "score": 7,
    "is_album": true,
    "vote": null,
    "favorite": false,
    "nsfw": false,
    "section": "",
    "comment_count": 4,
    "favorite_count": 0,
    "topic": null,
    "topic_id": null,
    "images_count": 1,
    "in_gallery": true,
    "is_ad": false,
    "tags": [
      {
        "name": "cats",
        "display_name": "cats",
        "followers": 212556,
        "total_items": 132433,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "xeEIpAn",
        "thumbnail_hash": null,
        "accent": "BF63A7",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "Our feline friends",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "meme",
        "display_name": "meme",
        "followers": 140207,
        "total_items": 88707,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "1fDftsZ",
        "thumbnail_hash": null,
        "accent": "ba519f",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "funny",
        "display_name": "Funny",
        "followers": 6648878,
        "total_items": 2667669,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "9r1qCDq",
        "thumbnail_hash": null,
        "accent": "633875",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "LOLs, ROFLs, LMAOs",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "memes",
        "display_name": "memes",
        "followers": 2773109,
        "total_items": 574056,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "1z4dgZT",
        "thumbnail_hash": null,
        "accent": "ba519f",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "the freshest memes",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "games",
        "display_name": "games",
        "followers": 9681,
        "total_items": 16304,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "yWpvDy6",
        "thumbnail_hash": null,
        "accent": null,
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "December 20th is International Games Day!",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      }
    ],
    "ad_type": 0,
    "ad_url": "",
    "in_most_viral": false,
    "include_album_ads": false,
    "images": [
      {
        "id": "W6BU06r",
        "title": null,
        "description": null,
        "datetime": 1671564905,
        "type": "image\/png",
        "animated": false,
        "width": 670,
        "height": 961,
        "size": 461165,
        "views": 62,
        "bandwidth": 28592230,
        "vote": null,
        "favorite": false,
        "nsfw": null,
        "section": null,
        "account_url": null,
        "account_id": null,
        "is_ad": false,
        "in_most_viral": false,
        "has_sound": false,
        "tags": [],
        "ad_type": 0,
        "ad_url": "",
        "edited": "0",
        "in_gallery": false,
        "link": "https:\/\/i.imgur.com\/W6BU06r.png",
        "comment_count": null,
        "favorite_count": null,
        "ups": null,
        "downs": null,
        "points": null,
        "score": null
      }
    ],
    "ad_config": {
      "safeFlags": [
        "album",
        "in_gallery",
        "gallery"
      ],
      "highRiskFlags": [],
      "unsafeFlags": [
        "sixth_mod_unsafe",
        "updated_date"
      ],
      "wallUnsafeFlags": [],
      "showsAds": false,
      "showAdLevel": 1,
      "safe_flags": [
        "album",
        "in_gallery",
        "gallery"
      ],
      "high_risk_flags": [],
      "unsafe_flags": [
        "sixth_mod_unsafe",
        "updated_date"
      ],
      "wall_unsafe_flags": [],
      "show_ads": false,
      "show_ad_level": 1
    }
  },
  {
    "id": "HAPa1bD",
    "title": "Imagem 2",
    "description": null,
    "datetime": 1671564948,
    "cover": "W6BU06r",
    "cover_width": 670,
    "cover_height": 961,
    "account_url": "Sodaman18",
    "account_id": 167021773,
    "privacy": "hidden",
    "layout": "blog",
    "views": 44,
    "link": "https:\/\/imgur.com\/a\/HAPa1bD",
    "ups": 9,
    "downs": 2,
    "points": 7,
    "score": 7,
    "is_album": true,
    "vote": null,
    "favorite": false,
    "nsfw": false,
    "section": "",
    "comment_count": 4,
    "favorite_count": 0,
    "topic": null,
    "topic_id": null,
    "images_count": 1,
    "in_gallery": true,
    "is_ad": false,
    "tags": [
      {
        "name": "cats",
        "display_name": "cats",
        "followers": 212556,
        "total_items": 132433,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "xeEIpAn",
        "thumbnail_hash": null,
        "accent": "BF63A7",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "Our feline friends",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "meme",
        "display_name": "meme",
        "followers": 140207,
        "total_items": 88707,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "1fDftsZ",
        "thumbnail_hash": null,
        "accent": "ba519f",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "funny",
        "display_name": "Funny",
        "followers": 6648878,
        "total_items": 2667669,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "9r1qCDq",
        "thumbnail_hash": null,
        "accent": "633875",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "LOLs, ROFLs, LMAOs",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "memes",
        "display_name": "memes",
        "followers": 2773109,
        "total_items": 574056,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "1z4dgZT",
        "thumbnail_hash": null,
        "accent": "ba519f",
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "the freshest memes",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      },
      {
        "name": "games",
        "display_name": "games",
        "followers": 9681,
        "total_items": 16304,
        "following": false,
        "is_whitelisted": false,
        "background_hash": "yWpvDy6",
        "thumbnail_hash": null,
        "accent": null,
        "background_is_animated": false,
        "thumbnail_is_animated": false,
        "is_promoted": false,
        "description": "December 20th is International Games Day!",
        "logo_hash": null,
        "logo_destination_url": null,
        "description_annotations": {}
      }
    ],
    "ad_type": 0,
    "ad_url": "",
    "in_most_viral": false,
    "include_album_ads": false,
    "images": [
      {
        "id": "W6BU06r",
        "title": null,
        "description": null,
        "datetime": 1671564905,
        "type": "image\/png",
        "animated": false,
        "width": 670,
        "height": 961,
        "size": 461165,
        "views": 62,
        "bandwidth": 28592230,
        "vote": null,
        "favorite": false,
        "nsfw": null,
        "section": null,
        "account_url": null,
        "account_id": null,
        "is_ad": false,
        "in_most_viral": false,
        "has_sound": false,
        "tags": [],
        "ad_type": 0,
        "ad_url": "",
        "edited": "0",
        "in_gallery": false,
        "link": "https:\/\/i.imgur.com\/W6BU06r.png",
        "comment_count": null,
        "favorite_count": null,
        "ups": null,
        "downs": null,
        "points": null,
        "score": null
      },
      {
        "id": "W6BU06r",
        "title": null,
        "description": null,
        "datetime": 1671564905,
        "type": "image\/png",
        "animated": false,
        "width": 670,
        "height": 961,
        "size": 461165,
        "views": 62,
        "bandwidth": 28592230,
        "vote": null,
        "favorite": false,
        "nsfw": null,
        "section": null,
        "account_url": null,
        "account_id": null,
        "is_ad": false,
        "in_most_viral": false,
        "has_sound": false,
        "tags": [],
        "ad_type": 0,
        "ad_url": "",
        "edited": "0",
        "in_gallery": false,
        "link": "https:\/\/i.imgur.com\/W6BU06r.png",
        "comment_count": null,
        "favorite_count": null,
        "ups": null,
        "downs": null,
        "points": null,
        "score": null
      }
    ],
    "ad_config": {
      "safeFlags": [
        "album",
        "in_gallery",
        "gallery"
      ],
      "highRiskFlags": [],
      "unsafeFlags": [
        "sixth_mod_unsafe",
        "updated_date"
      ],
      "wallUnsafeFlags": [],
      "showsAds": false,
      "showAdLevel": 1,
      "safe_flags": [
        "album",
        "in_gallery",
        "gallery"
      ],
      "high_risk_flags": [],
      "unsafe_flags": [
        "sixth_mod_unsafe",
        "updated_date"
      ],
      "wall_unsafe_flags": [],
      "show_ads": false,
      "show_ad_level": 1
    }
  }
]